Select
PROFILE_NAME,PROFILE_CODE,PROFILE_TYPE,INVOICE_ACCOUNT_NAME,INVOICE_ACCOUNT_CODE,SERVICE_ACCOUNT_LINK_CODE,OLD_ACCOUNT_CODE ,
SERVICE_ID,SERVICE_NAME,SUBSCRIBER_CATEGORY,SUBSCRIBER_SUB_CATEGORY,BUSINESS_TYPE,'"' || PACKAGE_NAME || '"',SERVICE_STATUS ,ACCOUNT_MANAGER,
LINK_DESCRIPTION ,UPLINK_SPEED,DOWNLINK_SPEED,IP_BANDWIDTH ,SOFT_SUSPENDED ,STATUS_DATE,START_DATE  ,
NO_CHARGE_FLAG,PRODUCT,SERVICE,TAX_PLAN,UNBILLED_USAGE ,BILL_CYCLE  ,CREDIT_LIMIT ,RENTALS  ,ADVANCE_PAID ,OUTSTANDING_BALANCE ,
CURRENT_BALANCE ,translate(CONTACT_PHONE_NUMBER, chr(10)||chr(11)||chr(13) , ' '),EMAIL_ADDRESS ,CONTACT_PERSON,TARIFF_CODE ,ACTIVATION_DATE_D ,SUSPENDED_DATE_D ,
PRE_TERMINATE_DATE_D ,REGISTRATION_DATE_D ,PROFILE_CREATION_DATE,ACCOUNT_CREATION_DATE ,CUST_SUPPORT_MANAGER,JOB_ORDER_CREATED_DT ,
JOB_ORDER_CLOSED_DT ,NON_RECURRING_CHARGE,NOMINATED_TM_MSISDN ,REGISTERED_MSISDN , PIN_REF_NUM  ,TM_CASCADE_FLG
FROM TT_MSO_1.BIB_AGL_FXL_STS_REPORT 
