SELECT TRANSLATE(TRANSLATE(TRANSLATE(PROCESS, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ')PROCESS,
       TRANSLATE(TRANSLATE(TRANSLATE(START_TIME, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ')START_TIME,
       TRANSLATE(TRANSLATE(TRANSLATE(END_TIME, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ')END_TIME,
       TO_CHAR(TO_DATE(START_TIME, 'dd/Mon/yyyy hh:mi:ss AM'),'yyyymmddhh24miss') DD
  FROM TT_MSO_1.BILL_RUN_STATISTICS_TAB
-- WHERE TRUNC(TO_DATE(START_TIME, 'dd/Mon/yyyy hh:mi:ss AM'), 'MONTH') = TO_DATE('${DATE}', 'yyyymm')
