SELECT
 ACCOUNT_LINK_CODE_N,      
 SERVICE_INFO_V,           
 PAY_AMT,                  
 CATEGORY_CODE_V,          
 PAYMENT_STATUS_V,         
 PAYMENT_DESCRIPTION_V,    
 REQUEST_TIME_D,           
 PAYMENT_REMARKS_V,        
 TRANS_NUM_V,              
 PAYMENT_METHOD_V,         
 PAYMENT_DESC_V,           
 SUBS_CATEGORY_DESC_V      
FROM TT_MSO_1.EXCESS_PAYMENT_RPT
