SELECT UNIQUE_ID,
       TRIM(LEADING 0 FROM TRIM(PHONE_NUMBER)) PHONE_NUMBER,
       B_ID,
       AGENT_ID,
       TO_CHAR(RECEIPT_TIMESTAMP, 'yyyymmdd hh24miss')
  FROM BIOCAPTURE.MULTIPLE_REG_BIB
 WHERE TRUNC(RECEIPT_TIMESTAMP) >= TO_DATE('${DATE}', 'yyyymmdd')
   AND TRUNC(RECEIPT_TIMESTAMP) < TO_DATE('${DATE}', 'yyyymmdd') + 1