select
TO_DATE(TO_CHAR(TRANS_DATE_D , 'yyyy-MM-DD HH:mm:ss'), 'yyyy-MM-DD HH:mi:ss') TRANS_DATE_D,
translate(SERVICE_INFO_V, chr(10)||chr(11)||chr(13) , ' '),
ACCOUNT_LINK_CODE_N,
translate(REFUND_TYPE_V, chr(10)||chr(11)||chr(13) , ' '),
AMOUNT_N,
translate(PACKAGE_CODE_V, chr(10)||chr(11)||chr(13) , ' '),
translate(USER_NAME_V, chr(10)||chr(11)||chr(13) , ' '),
translate(LOGIN_NAME_V, chr(10)||chr(11)||chr(13) , ' '),
translate(SUBS_NAME_V, chr(10)||chr(11)||chr(13) , ' '),
SUBSCRIBER_CODE_N,
translate(FIRST_NAME_V, chr(10)||chr(11)||chr(13) , ' '),
translate(PROFILE_TYPE_V, chr(10)||chr(11)||chr(13) , ' '),
translate(TICKET_TYPE_V, chr(10)||chr(11)||chr(13) , ' '),
translate(QUESTION_V, chr(10)||chr(11)||chr(13) , ' '),
translate(ANSWER_V, chr(10)||chr(11)||chr(13) , ' '),
translate(CATEGORY_DESCRIPTION_V, chr(10)||chr(11)||chr(13) , ' '),
translate(CATEGORY_CODE_V, chr(10)||chr(11)||chr(13) , ' '),
translate(TT_PARENT_CATE_DESC, chr(10)||chr(11)||chr(13) , ' '),
translate(TT_SUBCATE_CODE, chr(10)||chr(11)||chr(13) , ' '),
translate(TT_SUBCATE_DESC, chr(10)||chr(11)||chr(13) , ' '),
translate(TT_PARENT_CATE_CODE, chr(10)||chr(11)||chr(13) , ' ') from TT_MSO_1.COMPENSATION_prevmont
