SELECT 
   CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID,
   CHG_INFRASTRUCTURE_CHANGE.CHANGE_REQUEST_STATUS,
   CHG_INFRASTRUCTURE_CHANGE.Status_Reason,
   TRANSLATE(TRANSLATE(TRANSLATE(CHG_INFRASTRUCTURE_CHANGE.Description, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') Description,
   TRANSLATE(TRANSLATE(TRANSLATE(NVL2(CHG_INFRASTRUCTURE_CHANGE.Detailed_Description,1,0), CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') Detailed_Description,
   CHG_INFRASTRUCTURE_CHANGE.ServiceCI,
   NVL2(CHG_WorkLog_BJ.Detailed_Description,1,0) BJ,
   NVL2(CHG_WorkLog_TP.Detailed_Description,1,0) TP,
   NVL2(CHG_WorkLog_IP.Detailed_Description,1,0) IP,
   NVL2(CHG_WorkLog_BP.Detailed_Description,1,0) BP,
   NVL2(CHG_WorkLog_RA.Detailed_Description,1,0) RA,
   NVL2(CHG_WorkLog_SIA.Detailed_Description,1,0) SIA,
   CHG_INFRASTRUCTURE_CHANGE.Scheduled_Start_Date,
   TO_CHAR(TO_DATE('19700101', 'yyyymmdd') + ((CHG_INFRASTRUCTURE_CHANGE.Scheduled_Start_Date) / 24 / 60 / 60),'yyyymmddhh24miss') Scheduled_Start_Date_D,
   CHG_INFRASTRUCTURE_CHANGE.Scheduled_End_Date,
   CHG_INFRASTRUCTURE_CHANGE.Submit_Date,
   CHG_INFRASTRUCTURE_CHANGE.Change_Timing,
   CHG_INFRASTRUCTURE_CHANGE.ASGRP,
   CHG_INFRASTRUCTURE_CHANGE.ASCHG
FROM (
      SELECT * FROM ARADMIN.CHG_INFRASTRUCTURE_CHANGE
--         WHERE Scheduled_Start_Date >= ( to_date('20181201', 'yyyymmdd') - to_date('01-JAN-1970', 'DD-MON-YYYY') ) * (86400)
 --              AND Scheduled_Start_Date <= ( (to_date('${DATE}', 'yyyymmdd') + 1 ) - to_date('01-JAN-1970', 'DD-MON-YYYY') ) * (86400)
      ) CHG_INFRASTRUCTURE_CHANGE
LEFT OUTER JOIN ARADMIN.CHG_WORKLOG CHG_WorkLog_BP
   ON ( CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID = CHG_WorkLog_BP.INFRASTRUCTURE_CHANGE_ID ) AND ( CHG_WorkLog_BP.Work_Log_Type = 11000 )
LEFT OUTER JOIN ARADMIN.CHG_WORKLOG CHG_WorkLog_RA
   ON ( CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID = CHG_WorkLog_RA.INFRASTRUCTURE_CHANGE_ID ) AND ( CHG_WorkLog_RA.Work_Log_Type = 8000 )
LEFT OUTER JOIN ARADMIN.CHG_WORKLOG CHG_WorkLog_BJ
   ON ( CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID = CHG_WorkLog_BJ.INFRASTRUCTURE_CHANGE_ID ) AND ( CHG_WorkLog_BJ.Work_Log_Type = 3000 )
LEFT OUTER JOIN ARADMIN.CHG_WORKLOG CHG_WorkLog_TP
   ON ( CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID = CHG_WorkLog_TP.INFRASTRUCTURE_CHANGE_ID ) AND ( CHG_WorkLog_TP.Work_Log_Type = 16000 )
LEFT OUTER JOIN ARADMIN.CHG_WORKLOG CHG_WorkLog_SIA
   ON ( CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID = CHG_WorkLog_SIA.INFRASTRUCTURE_CHANGE_ID) AND ( CHG_WorkLog_SIA.Work_Log_Type = 9000 )
LEFT OUTER JOIN ARADMIN.CHG_WORKLOG CHG_WorkLog_IP
   ON ( CHG_INFRASTRUCTURE_CHANGE.INFRASTRUCTURE_CHANGE_ID = CHG_WorkLog_IP.INFRASTRUCTURE_CHANGE_ID ) AND ( CHG_WorkLog_IP.Work_Log_Type = 14000 )
