cp credit_information_mon/ojdbc6.jar DAY_TRANS_DETAIL/
cp credit_information_mon/ojdbc6.jar DBA_ROLE_PRIVS/
cp credit_information_mon/ojdbc6.jar DBA_TAB_PRIVS/
cp credit_information_mon/ojdbc6.jar FND_USER/
cp credit_information_mon/ojdbc6.jar FND_USER_ROLE/
cp credit_information_mon/ojdbc6.jar GEN_LED_VOUCHER/
cp credit_information_mon/ojdbc6.jar HISTORY_LOG/
cp credit_information_mon/ojdbc6.jar INVENTORY_PART_IN_STOCK/
cp credit_information_mon/ojdbc6.jar INVENTORY_TRANSACTION_HIST/
cp credit_information_mon/ojdbc6.jar LEDGER_ITEM_TAB/
cp credit_information_mon/ojdbc6.jar PAYMENT_ADDRESS_GENERAL/
cp credit_information_mon/ojdbc6.jar PAYMENT_TAB/
cp credit_information_mon/ojdbc6.jar PAYMENT_TERM/
cp credit_information_mon/ojdbc6.jar PRICE_LIST/
cp credit_information_mon/ojdbc6.jar PURCH_REQ_APPROVAL/
cp credit_information_mon/ojdbc6.jar PURCHASE_ORDER/
cp credit_information_mon/ojdbc6.jar PURCHASE_ORDER_APPROVAL/
cp credit_information_mon/ojdbc6.jar PURCHASE_ORDER_HIST/
cp credit_information_mon/ojdbc6.jar PURCHASE_ORDER_LINE/
cp credit_information_mon/ojdbc6.jar PURCHASE_RECEIPT_TAB/
cp credit_information_mon/ojdbc6.jar PURCHASE_REQ_LINE/
cp credit_information_mon/ojdbc6.jar PURCHASE_REQUISITION_TAB/
cp credit_information_mon/ojdbc6.jar RETURN_MATERIAL_LINE/
cp credit_information_mon/ojdbc6.jar SALES_PRICE_LIST_PART/
cp credit_information_mon/ojdbc6.jar SUPPLIER_INFO/
cp credit_information_mon/ojdbc6.jar SUPPLIER_INFO_ADDRESS/
