SELECT /*+ parallel(10)*/
 SERVICE_CODE_V,
 SERVICE_KEY_CODE_V,
 SERV_ACC_LINK_CODE_N,
 SCHEME_REF_CODE_N,
 PROFIT_CENTRE_CODE,
 COLLECTED_UPFRONT_V,
 PRIORITY_N,
 ACTION_PARM_STRG_V,
 TO_CHAR(PROCESS_ON_DATE_D AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') PROCESS_ON_DATE_D,
 STATUS_OPTN_V,
 CRITICAL_SERVICE_FLG_V,
 GROUP_CODE_V,
 TO_CHAR(EXECUTED_DT AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') EXECUTED_DT,
 USER_CODE_N,
 FROM_SELF_CARE_FLG_V,
 SCHDL_LINK_CODE_N,
 ACCOUNT_LINK_CODE_N,
 PROV_CHRONO_NUM_N,
 ORD_PROV_REQUEST_V,
 TO_CHAR(LAST_MODIFIED_DATE_D AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') LAST_MODIFIED_DATE_D,
 ACC_SERV_FLG_V,
 FAILURE_REASON_V,
 WAIVE_OFF_APPROVAL_V,
 UPLOAD_SEQUENCE_N,
 SESSION_TOKEN_V,
 (SELECT /*+ rule */
   MOBL_NUM_VOICE_V
    FROM TT_MSO_1.GSM_SERVICE_MAST
   WHERE A.SERV_ACC_LINK_CODE_N = ACCOUNT_LINK_CODE_N AND ROWNUM <= 1) MOBILE_NO

  FROM TT_MSO_1.CB_SCHEDULES A
 WHERE TRUNC(PROCESS_ON_DATE_D AT TIME ZONE 'Africa/Algiers') >= TO_DATE('${DATE}', 'yyyymmdd')
   AND TRUNC(PROCESS_ON_DATE_D AT TIME ZONE 'Africa/Algiers') < TO_DATE('${DATE}', 'yyyymmdd') +1
   