select
  MSISDN                   
 ,SERVICE_CLASS_ID        
 ,DA_VOICE                
 ,DA_SMS                  
 ,DA_DATA                 
 ,DA_VAS                  
 ,DA_SUBSCRIPTION         
 ,DA_ROAMING_VOICE        
 ,DA_ROAMING_SMS          
 ,DA_ROAMING_DATA         
 ,DA_ROAMING_VAS          
 ,CREDIT_LIMIT            
 ,OUTSTANDING_CREDIT_LIMIT
 ,SDP_CREDIT_LIMIT_USEAGE 
 ,AGL_CREDIT_LIMIT_USAGE  
 ,AGL_DA_MOVEMENT         
 ,MA_VOICE                
 ,MA_SMS                  
 ,MA_DATA                 
 ,MA_VAS                  
 ,MA_SUBSCRIPTION         
 ,MA_ROAMING_VOICE        
 ,MA_ROAMING_SMS          
 ,MA_ROAMING_DATA         
 ,MA_ROAMING_VAS          
 ,DA_CREDIT_ADJ           
 ,DA_DEBIT_ADJ            
 ,DA_PAYMENT              
 ,MA_CREDIT_ADJ           
 ,MA_DEBIT_ADJ            
 ,MA_PAYMENT              
 ,AGL_MAIN_AC_USAGE       
 ,TOTAL_USAGE             
 ,CUG                     
 ,MAIN_ACT_OPEN_BAL       
 ,MAIN_ACT_CLOSE_BAL      
 ,AGL_USAGE               
 ,SDP_MAIN_ACT_MOVEMENT   
 ,AGL_MAIN_ACT_MOVEMENT   
 ,BILLING_SDP_VARIANCE    
 ,REMARK                  
 ,APPLY_INVOICE           
 ,PREV_MONTH_INV          
 ,OTHER_DA_VOICE          
 ,OTHER_DA_SMS            
 ,OTHER_DA_DATA           
 ,OTHER_DA_VAS            
 ,OTHER_DA_SUBSCRIPTION   
 ,OTHER_DA_ROAMING_VOICE  
 ,OTHER_DA_ROAMING_SMS    
 ,OTHER_DA_ROAMING_DATA   
 ,OTHER_DA_ROAMING_VAS    
 ,AGL_OTHER_DA_USAGE      
 ,DA_XTRA_SUBS            
 ,TEMP_CREDIT_LIMIT       
 ,ROAM_CREDIT_LIMIT       
 from TT_MSO_1.AGL_BILL_ANALYZER_MONTHLY_
 --${DATE}
