select  PART_NO, 
LOCATION_NO, 
WAIV_DEV_REJ_NO, 
TRANSACTION, 
COST, 
DATE_APPLIED, 
DIRECTION, 
QUANTITY, 
USERID, 
DATE_CREATED, 
DATE_TIME_CREATED, 
PALLET_ID, 
RECEIPT_DATE  from IFSAPP.INVENTORY_TRANSACTION_HIST  WHERE SUBSTR(TRANSACTION_ID,-1,1)='${MSSDN}'



