SELECT /*+ parallel(6) */
 SITE,
 LOCATION_NO,
 TO_CHAR(DATED, 'yyyymmdd hh24miss') DATED,
 TRANSACTION_CODE,
 TRANSACTION_TYPE,
 PART_NO,
 ORDER_NO,
 DESCRIPTION,
 ASSET_CLASS,
 SALES_QUANTITY,
 SALES_VALUE,
 SALES_COST
  FROM IFSAPP.IFSCONNECT_SALES_HIST
 WHERE DATED = TO_DATE('${DATE}', 'yyyyMMdd')

