select PK,              
ACTIVE,          
TO_DATE(TO_CHAR(CREATE_DATE, 'yyyy-MM-DD HH:mm:ss'), 'yyyy-MM-DD HH:mi:ss') CREATE_DATE,    
DELETED,         
LAST_MODIFIED,   
BLACKLISTED_ITEM,
ITEM_TYPE,       
REVOKED,         
MAC_ADDRESS,     
ENROLLMENT_REF  from BIOCAPTURE.kyc_blacklist  
