 SELECT
    TRANSLATE(TRANSLATE(TRANSLATE(CUSTOMER_ID, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') CUSTOMER_ID,
    TRANSLATE(TRANSLATE(TRANSLATE(NAME, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') NAME,
    TO_CHAR(CREATION_DATE,'yyyymmdd hh24miss') CREATION_DATE,
    TRANSLATE(TRANSLATE(TRANSLATE(ASSOCIATION_NO, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') ASSOCIATION_NO,
    TRANSLATE(TRANSLATE(TRANSLATE(PARTY, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') PARTY,
    TRANSLATE(TRANSLATE(TRANSLATE(DEFAULT_DOMAIN, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') DEFAULT_DOMAIN,
    TRANSLATE(TRANSLATE(TRANSLATE(DEFAULT_LANGUAGE, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') DEFAULT_LANGUAGE,
    TRANSLATE(TRANSLATE(TRANSLATE(COUNTRY, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') COUNTRY,
    TRANSLATE(TRANSLATE(TRANSLATE(PARTY_TYPE, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') PARTY_TYPE,
    ROWVERSION,
    TRANSLATE(TRANSLATE(TRANSLATE(CORPORATE_FORM, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') CORPORATE_FORM,
    TRANSLATE(TRANSLATE(TRANSLATE(IDENTIFIER_REFERENCE, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') IDENTIFIER_REFERENCE,
    TRANSLATE(TRANSLATE(TRANSLATE(IDENTIFIER_REF_VALIDATION, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') IDENTIFIER_REF_VALIDATION,
    TEXT_ID$ TEXT_ID,
    PICTURE_ID
 FROM IFSAPP.CUSTOMER_INFO_TAB