bash CB_SCHEDULES_LIVE.sh 20190117 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190118 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190119 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190120 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190121 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190122 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190123 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190124 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190125 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190126 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190127 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190128 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190129 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190130 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190131 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190201 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190202 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190203 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190204 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190205 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190206 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190207 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190208 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190209 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190210 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190211 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190212 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190213 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190214 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190215 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190216 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190217 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190218 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190219 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190220 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190221 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190222 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190223 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190224 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190225 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190226 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190227 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190228 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190301 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190302 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190303 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190304 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt
bash CB_SCHEDULES_LIVE.sh 20190305 2>&1 tee /mnt/beegfs/tools/ExtractTools/CB_SCHEDULES_LIVE/logs/CB_SCHEDULES_LIVE_extract_today_$(date +%Y%m%d_%H%M%S).txt

