SELECT /*+ parallel(10)*/
 SERVICE_CODE_V,
 SERV_ACC_LINK_CODE_N,
 SERVICE_INFO_V,
 SERVICE_KEY_CODE_V,
 CONTRACT_TYPE_V,
 STATUS_CODE_V,
 REGISTRATION_DATE_D,
 UPDATE_DT_D,
 PROCESS_ON_DATE_D,
 EXECUTED_DT,
 FROM_DATE_D,
 SEQ_NO_N,
 SIM_REG_STATUS_V,
 PART_SUBSIDIARY_V,
 LAST_MODIFIED_DATE_D,
 SEAM_REGISTRATION_DATE,
 TO_CHAR(UPDATE_DT_D, 'YYYY-MM-DD HH24:MI:ss') AS FORMAT_DATE
  FROM TT_MSO_1.MSO_PROCESS_AVG_TIME
 WHERE TRUNC(UPDATE_DT_D AT TIME ZONE 'Africa/Algiers') >= TO_DATE('${DATE}', 'YYYYMMDD')
   AND TRUNC(UPDATE_DT_D AT TIME ZONE 'Africa/Algiers') < (TO_DATE('${DATE}', 'YYYYMMDD') + 1)
