select
TO_DATE(TO_CHAR(TRANS_DATE_D , 'yyyy-MM-DD HH:mm:ss'), 'yyyy-MM-DD HH:mi:ss') TRANS_DATE_D
,SR_TT 
,COMPENSATION_TYPE  
,'SR/TT_TYPE'  
,CATECORY  
,SUB_CATEGORY  
,PLAN_TYPE  
,USER_FIRST_NAME  
,USER_LAST_NAME  
,MSISDN  
,AMOUNT_COMPENSATED 
,USER_NAME  
,PRIORITY 
,CREATED_DATE  
,STATUS  
,COMMENTS  
,SEGMENT  
,'COMPENSATION_STATUS'  
from tt_mso_1.compensation
