select
msisdn_key as MSISDN_NSK,
DATE_KEY,
case when try_cast(substr(cast(coalesce(TOTAL_OG_MOU,0) as varchar),index(cast(coalesce(TOTAL_OG_MOU,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(TOTAL_OG_MOU,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(TOTAL_OG_MOU,0) as varchar),1,index(cast(coalesce(TOTAL_OG_MOU,0) as varchar),'.')-1) end as TOTAL_OG_MOU,
case when try_cast(substr(cast(coalesce(TOTAL_DATA_PAYGO_USAGE,0) as varchar),index(cast(coalesce(TOTAL_DATA_PAYGO_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(TOTAL_DATA_PAYGO_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(TOTAL_DATA_PAYGO_USAGE,0) as varchar),1,index(cast(coalesce(TOTAL_DATA_PAYGO_USAGE,0) as varchar),'.')-1) end as TOTAL_DATA_PAYGO_USAGE,
case when try_cast(substr(cast(total_data_bundled_usage as varchar),index(cast(total_data_bundled_usage as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(total_data_bundled_usage,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(total_data_bundled_usage,0) as varchar),1,index(cast(coalesce(total_data_bundled_usage,0) as varchar),'.')-1) end as TOTAL_DATA_BUNDLE_USAGE,
case when try_cast(substr(cast(coalesce(TOTAL_DATA_USAGE,0) as varchar),index(cast(coalesce(TOTAL_DATA_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(TOTAL_DATA_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(TOTAL_DATA_USAGE,0) as varchar),1,index(cast(coalesce(TOTAL_DATA_USAGE,0) as varchar),'.')-1) end as TOTAL_DATA_USAGE,
case when try_cast(substr(cast(coalesce(DATA_4G_PAYGO_USAGE,0) as varchar),index(cast(coalesce(DATA_4G_PAYGO_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(DATA_4G_PAYGO_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(DATA_4G_PAYGO_USAGE,0) as varchar),1,index(cast(coalesce(DATA_4G_PAYGO_USAGE,0) as varchar),'.')-1) end as DATA_4G_PAYGO_USAGE,
case when try_cast(substr(cast(coalesce(DATA_4G_BUNDLED_USAGE,0) as varchar),index(cast(coalesce(DATA_4G_BUNDLED_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(DATA_4G_BUNDLED_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(DATA_4G_BUNDLED_USAGE,0) as varchar),1,index(cast(coalesce(DATA_4G_BUNDLED_USAGE,0) as varchar),'.')-1) end as DATA_4G_BUNDLED_USAGE,
case when try_cast(substr(cast(coalesce(DATA_3G_PAYGO_USAGE,0) as varchar),index(cast(coalesce(DATA_3G_PAYGO_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(DATA_3G_PAYGO_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(DATA_3G_PAYGO_USAGE,0) as varchar),1,index(cast(coalesce(DATA_3G_PAYGO_USAGE,0) as varchar),'.')-1) end as DATA_3G_PAYGO_USAGE,
case when try_cast(substr(cast(coalesce(DATA_3G_BUNDLED_USAGE,0) as varchar),index(cast(coalesce(DATA_3G_BUNDLED_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(DATA_3G_BUNDLED_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(DATA_3G_BUNDLED_USAGE,0) as varchar),1,index(cast(coalesce(DATA_3G_BUNDLED_USAGE,0) as varchar),'.')-1) end as DATA_3G_BUNDLED_USAGE,
case when try_cast(substr(cast(coalesce(DATA_2G_PAYGO_USAGE,0) as varchar),index(cast(coalesce(DATA_2G_PAYGO_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(DATA_2G_PAYGO_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(DATA_2G_PAYGO_USAGE,0) as varchar),1,index(cast(coalesce(DATA_2G_PAYGO_USAGE,0) as varchar),'.')-1) end as DATA_2G_PAYGO_USAGE,
case when try_cast(substr(cast(coalesce(DATA_2G_BUNDLED_USAGE,0) as varchar),index(cast(coalesce(DATA_2G_BUNDLED_USAGE,0) as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(coalesce(DATA_2G_BUNDLED_USAGE,0) as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(coalesce(DATA_2G_BUNDLED_USAGE,0) as varchar),1,index(cast(coalesce(DATA_2G_BUNDLED_USAGE,0) as varchar),'.')-1) end as DATA_2G_BUNDLED_USAGE,
coalesce(TOTAL_SMS_COUNT,0) as TOTAL_SMS_CNT
from nigeria.cm_usg_realtime_sit_f;