select
msisdn_key as MSISDN_NSK,
DATE_KEY,
case when try_cast(substr(cast(ONNET_IC_REVENUE as varchar),index(cast(ONNET_IC_REVENUE as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(ONNET_IC_REVENUE as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(ONNET_IC_REVENUE as varchar),1,index(cast(ONNET_IC_REVENUE as varchar),'.')-1) end as ONNET_IC_REVENUE,
case when try_cast(substr(cast(OFFNET_IC_REVENUE as varchar),index(cast(OFFNET_IC_REVENUE as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(OFFNET_IC_REVENUE as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(OFFNET_IC_REVENUE as varchar),1,index(cast(OFFNET_IC_REVENUE as varchar),'.')-1) end as OFFNET_IC_REVENUE,
case when try_cast(substr(cast(idd_roaming_ic_revenue as varchar),index(cast(idd_roaming_ic_revenue as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(idd_roaming_ic_revenue as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(idd_roaming_ic_revenue as varchar),1,index(cast(idd_roaming_ic_revenue as varchar),'.')-1) end as ROAMING_IC_REVENUE,
case when try_cast(substr(cast(idd_roaming_incoming_usage as varchar),index(cast(idd_roaming_incoming_usage as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(idd_roaming_incoming_usage as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(idd_roaming_incoming_usage as varchar),1,index(cast(idd_roaming_incoming_usage as varchar),'.')-1) end as ROAMING_INCOMING_USAGE,
coalesce(idd_ROAMING_IC_CALL_COUNT,0) as ROAMING_IC_CALL_COUNT,
case when try_cast(substr(cast(ONNET_IC_MOU as varchar),index(cast(ONNET_IC_MOU as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(ONNET_IC_MOU as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(ONNET_IC_MOU as varchar),1,index(cast(ONNET_IC_MOU as varchar),'.')-1) end as ONNET_IC_MOU,
case when try_cast(substr(cast(OFFNET_IC_MOU as varchar),index(cast(OFFNET_IC_MOU as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(OFFNET_IC_MOU as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(OFFNET_IC_MOU as varchar),1,index(cast(OFFNET_IC_MOU as varchar),'.')-1) end as OFFNET_IC_MOU,
case when try_cast(substr(cast(IDD_IC_MOU as varchar),index(cast(IDD_IC_MOU as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(IDD_IC_MOU as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(IDD_IC_MOU as varchar),1,index(cast(IDD_IC_MOU as varchar),'.')-1) end as IDD_IC_MOU,
case when try_cast(substr(cast(TOTAL_IC_MOU as varchar),index(cast(TOTAL_IC_MOU as varchar),'.')+1) as integer)>0 then try_cast(try_cast(try_cast(cast(TOTAL_IC_MOU as varchar) as decimal(18,2)) as double) as varchar) else substr(cast(TOTAL_IC_MOU as varchar),1,index(cast(TOTAL_IC_MOU as varchar),'.')-1) end as TOTAL_IC_MOU
from nigeria.cm_usg_voice_ic_sit_f;