bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180217
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180219
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180223
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180224
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180225
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180226
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180227
bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_GPRS_MA	--date	20180228
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20171205
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20171220
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20171221
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20180101
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20180112
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20180208
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20180216
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_SMS_MA	--date	20180220
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20171220
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180112
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180115
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180129
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180208
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180215
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180216
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_DA	--date	20180220
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_MA	--date	20171220
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_MA	--date	20171224
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_MA	--date	20180112
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_MA	--date	20180115
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_MA	--date	20180129
#bash run_reprocess.sh --config ./reprocess.conf --feed 	CS5_CCN_VOICE_MA	--date	20180208
#bash run_reprocess.sh --config ./reprocess.conf --feed 	DMC_DUMP_ALL	--date	20171224
#bash run_reprocess.sh --config ./reprocess.conf --feed 	DMC_DUMP_ALL	--date	20171225
#bash run_reprocess.sh --config ./reprocess.conf --feed 	DMC_DUMP_ALL	--date	20180127
#bash run_reprocess.sh --config ./reprocess.conf --feed 	DMC_DUMP_ALL	--date	20180211
#bash run_reprocess.sh --config ./reprocess.conf --feed 	MSC_CDR	--date	20180225
#bash run_reprocess.sh --config ./reprocess.conf --feed 	SDP_DMP_MA	--date	20171205
#bash run_reprocess.sh --config ./reprocess.conf --feed 	SDP_DMP_MA	--date	20171214
#bash run_reprocess.sh --config ./reprocess.conf --feed 	SDP_DMP_MA	--date	20171224
#bash run_reprocess.sh --config ./reprocess.conf --feed 	SDP_DMP_MA	--date	20180122
#bash run_reprocess.sh --config ./reprocess.conf --feed 	SDP_DMP_MA	--date	20180208
#bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180101
#bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180110
#bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180201
