bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180108
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180130
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180109
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180110
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180127
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180124
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180129
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180125
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180126
bash run_reprocess.sh --config ./reprocess.conf --feed  GGSN_CDR --date 20180128
bash run_reprocess.sh --config ./reprocess.conf --feed  MSC_CDR --date 20180131
bash run_reprocess.sh --config ./reprocess.conf --feed  MSC_CDR --date 20180108
bash run_reprocess.sh --config ./reprocess.conf --feed  MSC_CDR --date 20180126
bash run_reprocess.sh --config ./reprocess.conf --feed  MSC_CDR --date 20180130
bash run_reprocess.sh --config ./reprocess.conf --feed  MSC_CDR --date 20180127
bash run_reprocess.sh --config ./reprocess.conf --feed  MSC_CDR --date 20180110
