bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_GPRS_MA  --date 20180126	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_VOICE_MA --date 20180126	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_SDP_ACC_ADJ_MA --date 20180126	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_AIR_REFILL_MA  --date 20180126 	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_VOICE_DA --date 20180127	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_VOICE_MA --date 20180127	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_SDP_ACC_ADJ_MA --date 20180127	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_AIR_REFILL_MA  --date 20180127 	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_GPRS_MA  --date 20180129	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_VOICE_DA --date 20180129	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_VOICE_MA --date 20180129	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_SDP_ACC_ADJ_MA --date 20180129	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_AIR_REFILL_MA  --date 20180129 	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_GPRS_MA  --date 20180130	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_CCN_VOICE_MA --date 20180130	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_SDP_ACC_ADJ_MA --date 20180130	
bash run_reprocess.sh --config ./reprocess.conf --feed CS5_AIR_REFILL_MA  --date 20180130
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180104
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180105
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180109
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180111
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180112
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180113
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180201
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180206
