bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180216
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180217
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180218
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180220
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180221
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180222
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180224
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180225
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180226
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180227
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180228
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180301
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180302
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180303
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180304
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180305
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180306
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180307
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180308
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180309
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180310
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180311
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180312
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180313
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180314
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180315
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180316
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180317
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180318
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180319
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180320
bash run_reprocess.sh --config ./reprocess.conf --feed WBS_PM_RATED_CDRS --date 20180321
