SELECT /*+ parallel(10)*/
    PK,
    ACTIVE,
    TO_CHAR(CREATE_DATE AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') CREATE_DATE,
    DELETED,
    TO_CHAR(LAST_MODIFIED AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') LAST_MODIFIED,
    TO_CHAR(EXPIRATION_TIME AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') EXPIRATION_TIME,
    MSISDN,
    OTP,
    OTP_USED,
    TO_CHAR(TIME_GENERATED AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') TIME_GENERATED,
    TO_CHAR(TIME_USED AT TIME ZONE 'Africa/Algiers', 'yyyymmddhh24miss') TIME_USED,
    OTP_STATUS_RECORD_TYPE_ENUM
FROM BIOCAPTURE.OTP_STATUS_RECORD
WHERE CREATE_DATE BETWEEN TO_DATE('20190701 000000','YYYYMMDD HH24MISS') AND TO_DATE('20190815 235959','YYYYMMDD HH24MISS')
