start transaction;
insert into engine_room.EVD_STOCK_LEVEL 
(select to_hex(sha1(to_utf8(msisdn))) as msisdn,balancevalueafter,original_timestamp_enrich,kamanja_loaded_date,transaction_type,tbl_dt FROM ( select coalesce (receivermsisdn,'') as msisdn , coalesce(receiverbalancevalueafter ,0.0) as balancevalueafter , coalesce(original_timestamp_enrich ,'') as original_timestamp_enrich , kamanja_loaded_date , case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end as transaction_type , yyyymmddRunDate as tbl_dt 
from flare_8.ERS_VEND_NEW 
where tbl_dt = yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_IN') 
UNION ALL 
select coalesce (sendermsisdn,'') as msisdn , coalesce(senderbalancevalueafter ,0.0) as balancevalueafter , coalesce(original_timestamp_enrich ,'') as original_timestamp_enrich , kamanja_loaded_date , case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end as transaction_type , yyyymmddRunDate as tbl_dt 
from flare_8.ERS_VEND_NEW 
where tbl_dt = yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_OUT') 
UNION ALL 
select coalesce (sendermsisdn,'') as msisdn , coalesce(senderbalancevalueafter ,0.0) as balancevalueafter , coalesce(original_timestamp_enrich ,'') as original_timestamp_enrich , kamanja_loaded_date , case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end as transaction_type , yyyymmddRunDate as tbl_dt
from flare_8.ERS_VEND_NEW 
where tbl_dt = yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_THROUGH') 
UNION ALL 
select coalesce (receivermsisdn,'') as msisdn , coalesce(receiverbalancevalueafter ,0.0) as balancevalueafter , coalesce(original_timestamp_enrich ,'') as original_timestamp_enrich , kamanja_loaded_date , case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end as transaction_type , yyyymmddRunDate as tbl_dt 
from flare_8.ERS_VEND_NEW 
where tbl_dt = yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_THROUGH') ))
;commit;
