SELECT REQUISITION_NO,
       LINE_NO,
       RELEASE_NO,
       PART_NO,
       DESCRIPTION,
       SITE,
       STATUS,
       QUANTITY,
       U_M,
       PURCH_UM,
       PRICE_CURR,
       CURRENCY_CODE,
       PRICE_BASE,
       DISCOUNT,
       ADDITIONAL_COST,
       TOTAL_COST_PRICE,
       TOTAL_BASE,
       TOTAL,
       SUPPLIER,
       SUPPLIER_NAME,
       PURCHASE_GROUP,
       TO_CHAR(WANTED_RECEIPT_DATE, 'yyyymmddhh24miss') WANTED_RECEIPT_DATE,
       TO_CHAR(ORDER_DATE, 'yyyymmddhh24miss') ORDER_DATE,
       REQUISITION_STATUS,
       REQUISITIONER,
       REQUISITIONER_NAME,
       PO_NO,
       PO_RELNO,
       PO_LINENO,
       ACCOUNT,
       SEGMENT,
       CC_R,
       PRICE_PLAN,
       FA,
       PROJECT,
       SUBLEDGER,
       ACC_SITE,
       CODE_J
  FROM IFSAPP.MTN_PR_DETAILS
 WHERE ORDER_DATE >= TO_DATE('${DATE}', 'yyyymmdd')
   AND ORDER_DATE <= TO_DATE('${DATE}', 'yyyymmdd')
