start transaction;
insert into cvm_db.cvm20_device
(msisdn_key,yearid,monthid,weekid,week_started,week_ended,imei,imsi,last_detection,msc_gt,last_configuration,billing,tac,brand,model_name,device_category,software_os_vendor,software_os_name,software_os_version,ota,data,weight,screen_size,screen_reso,mms_receiver,wap_support,wapversion,internet,hardware_gprs,hardware_edge,hardware_hsdpa,hardware_hsupa,camera,camera_reso,memorycard,gps,video,streaming_video,radiofm,audio_amr,audio_mp3,bluetooth,wlan,ptt,syncmlds,omadm,nw_2g,nw_3g,nw_4g,hardware_lte,hardware_nfc,sim_form_factor,edge_ind,gprs_ind,number_of_sim,display_width,display_height,display_depth,display_touchscreen,lte_frequencies,hardware_wifi,brand_name,tbl_dt ) 
select 
sub.msisdn_key   ,
sub.YearID ,sub.monthid,sub.WeekID ,sub.week_started
,sub.week_ended,
 device.imei                ,        
 device.imsi                ,        
 device.last_detection      ,        
 device.msc_gt              ,        
 device.last_configuration  ,        
 device.billing             ,        
 device.tac                 ,        
 device.brand               ,        
 device.model_name          ,        
 device.device_category     ,        
 device.software_os_vendor  ,        
 device.software_os_name    ,        
 device.software_os_version ,        
 device.ota                 ,        
 device.data                ,        
 device.weight              ,        
 device.screen_size         ,        
 device.screen_reso         ,        
 device.mms_receiver        ,        
 device.wap_support         ,        
 device.wapversion          ,        
 device.internet            ,        
 device.hardware_gprs       ,        
 device.hardware_edge       ,        
 device.hardware_hsdpa      ,        
 device.hardware_hsupa      ,        
 device.camera              ,        
 device.camera_reso         ,        
 device.memorycard          ,        
 device.gps                 ,        
 device.video               ,        
 device.streaming_video     ,        
 device.radiofm             ,        
 device.audio_amr           ,        
 device.audio_mp3           ,        
 device.bluetooth           ,        
 device.wlan                ,        
 device.ptt                 ,        
 device.syncmlds            ,        
 device.omadm               ,        
 device.nw_2g               ,        
 device.nw_3g               ,        
 device.nw_4g               ,        
 device.hardware_lte        ,        
 device.hardware_nfc        ,        
 device.sim_form_factor     ,        
 device.edge_ind            ,        
 device.gprs_ind            ,        
 device.number_of_sim       ,        
 device.display_width       ,        
 device.display_height      ,        
 device.display_depth       ,        
 device.display_touchscreen ,        
 device.lte_frequencies     ,        
 device.hardware_wifi       ,        
 device.brand_name          ,
sub.tbl_dt
from cvm_db.cvm20_device_tmp device 
inner join cvm_db.cvm20_subs_tmp sub 
on sub.msisdn_key=device.msisdn_key and sub.tbl_dt=device.tbl_dt     
where sub.dola <= 180 and sub.tbl_dt = yyyymmddRunDate;
commit;
