start transaction;
delete from cvm_db.CVM20_USG_DATA_SMS_VOI_PRD_TMP where tbl_dt=yyyymmddRunDate;
insert into cvm_db.cvm20_usg_data_sms_voi_prd_tmp
(msisdn_key , voi_offnet_out_c_count , voi_offnet_out_nc_count, voi_onnet_out_c_count, voi_onnet_out_nc_count , voi_int_out_c_count,
voi_int_out_nc_count , voi_offnet_out_b_count , voi_offnet_out_nb_count, voi_onnet_out_b_count, voi_onnet_out_nb_count , 
voi_int_out_b_count, voi_int_out_nb_count , voi_offnet_out_free_count, voi_onnet_out_free_count , voi_int_out_free_count , 
voi_offnet_out_c_sec , voi_offnet_out_nc_sec, voi_onnet_out_c_sec, voi_onnet_out_nc_sec , voi_int_out_c_sec, voi_int_out_nc_sec , 
voi_offnet_out_b_sec , voi_offnet_out_nb_sec, voi_onnet_out_b_sec, voi_onnet_out_nb_sec , voi_int_out_b_sec, voi_int_out_nb_sec , 
voi_offnet_out_free_sec, voi_onnet_out_free_sec , voi_int_out_free_sec , voi_roam_out_free_sec, voi_roam_in_free_sec , voi_roam_out_sec , 
voi_roam_out_free_count, voi_roam_in_free_count , voi_roam_out_count , voi_fix_out_free_count , voi_fix_out_free_sec , voi_fix_out_count,
voi_fix_out_sec, voi_fix_in_count , voi_fix_in_sec , voi_cc_out_count , voi_cc_out_sec , voi_cc_in_count, voi_cc_in_sec, sn_voi_total_mtc , 
sn_voi_total_moc , voi_offnet_in_count, voi_onnet_in_count , voi_roam_in_count, voi_int_in_count , voi_offnet_in_sec, voi_onnet_in_sec ,
voi_roam_in_sec, voi_int_in_sec , voi_out_sec, voi_out_count, voi_in_count , voi_in_sec,sms_onnet_in_count, sms_offnet_in_count, sms_int_in_count, sms_in_count , voi_out_count_bundle , voi_out_duration_bundle,
voi_out_count_payg , voi_out_duration_payg, fnf_call_tot_sec , fnf_call_count , weekday_voi_count, weekday_voi_sec, weekend_voi_count, 
weekend_voi_sec, weekday_voi_onnet_count, weekday_voi_onnet_sec, weekend_voi_onnet_count, weekend_voi_onnet_sec, weekday_voi_offnet_count , 
weekday_voi_offnet_sec , weekend_voi_offnet_count , weekend_voi_offnet_sec , weekday_voi_intl_count , weekday_voi_intl_sec , 
weekend_voi_intl_count , weekend_voi_intl_sec , weekday_voi_roam_count , weekday_voi_roam_sec , weekend_voi_roam_count , 
weekend_voi_roam_sec , morning_voi_out_sec, afternoon_voi_out_sec, evening_voi_out_sec, night_voi_out_sec, peak_voi_out_sec , 
non_peak_voi_out_sec , voi_volte_count, voi_volte_sec, call_drop_rate , call_success_rate, yearid, monthid , weekid, week_started ,
week_ended , tbl_dt) 
select sub.msisdn_key ,
usg_dat_voi_sms.voi_offnet_out_c_count, 
usg_dat_voi_sms.voi_offnet_out_nc_count,
usg_dat_voi_sms.voi_onnet_out_c_count,
usg_dat_voi_sms.voi_onnet_out_nc_count ,
usg_dat_voi_sms.voi_int_out_c_count,
usg_dat_voi_sms.voi_int_out_nc_count ,
usg_dat_voi_sms.voi_offnet_out_b_count ,
usg_dat_voi_sms.voi_offnet_out_nb_count,
usg_dat_voi_sms.voi_onnet_out_b_count ,
voi_onnet_out_nb_count ,
voi_int_out_b_count,
voi_int_out_nb_count ,
voi_offnet_out_free_count,
voi_onnet_out_free_count ,
voi_int_out_free_count ,
voi_offnet_out_c_sec ,
voi_offnet_out_nc_sec,
voi_onnet_out_c_sec,
voi_onnet_out_nc_sec ,
voi_int_out_c_sec,
voi_int_out_nc_sec ,
voi_offnet_out_b_sec ,
voi_offnet_out_nb_sec,
voi_onnet_out_b_sec,
voi_onnet_out_nb_sec ,
voi_int_out_b_sec,
voi_int_out_nb_sec ,
voi_offnet_out_free_sec,
voi_onnet_out_free_sec ,
voi_int_out_free_sec ,
voi_roam_out_free_sec,
voi_roam_in_free_sec ,
voi_roam_out_sec ,
voi_roam_out_free_count,
voi_roam_in_free_count ,
voi_roam_out_count, 
cast(null as bigint)  voi_fix_out_free_count,
cast(null as double)  voi_fix_out_free_sec,
cast(null as bigint)  voi_fix_out_count,
cast(null as double)   voi_fix_out_sec,
cast(null as bigint)   voi_fix_in_count,
cast(null as double)  voi_fix_in_sec,
cs2.voi_cc_out_count,
cs2.voi_cc_out_sec ,
cast(null  as bigint)  voi_cc_in_count      ,
cast(null as double)   voi_cc_in_sec       , 
cs2.sn_voi_total_mtc  ,
cs2.sn_voi_total_moc ,
vsi.voi_offnet_in_count,
vsi.voi_onnet_in_count ,
voi_roam_in_count,
vsi.voi_int_in_count ,
vsi.voi_offnet_in_sec,
vsi.voi_onnet_in_sec ,
voi_roam_in_sec,
vsi.voi_int_in_sec ,
usg_dat_voi_sms.voi_out_sec   ,
usg_dat_voi_sms.voi_out_count   ,
vsi.voi_in_count ,
vsi.voi_in_sec  ,
vsi.sms_onnet_in_count,
vsi.sms_offnet_in_count,
vsi.sms_int_in_count,
vsi.sms_in_count,
usg_dat_voi_sms.voi_out_count_bundle  ,
voi_out_duration_bundle,
voi_out_count_payg,
voi_out_duration_payg,
cast(null  as double)   fnf_call_tot_sec ,
cast(null as bigint)   fnf_call_count ,
usg_dat_voi_sms.weekday_voi_count         ,
usg_dat_voi_sms.weekday_voi_sec           ,
usg_dat_voi_sms.weekend_voi_count         ,
usg_dat_voi_sms.weekend_voi_sec           ,
usg_dat_voi_sms.weekday_voi_onnet_count   ,
usg_dat_voi_sms.weekday_voi_onnet_sec     ,
usg_dat_voi_sms.weekend_voi_onnet_count   ,
usg_dat_voi_sms.weekend_voi_onnet_sec    ,
usg_dat_voi_sms.weekday_voi_offnet_count  ,
usg_dat_voi_sms.weekday_voi_offnet_sec    ,
usg_dat_voi_sms.weekend_voi_offnet_count  ,
usg_dat_voi_sms.weekend_voi_offnet_sec   ,
usg_dat_voi_sms.weekday_voi_intl_count    ,
usg_dat_voi_sms.weekday_voi_intl_sec      ,
usg_dat_voi_sms.weekend_voi_intl_count    ,
usg_dat_voi_sms.weekend_voi_intl_sec     ,
usg_dat_voi_sms.weekday_voi_roam_count    ,
usg_dat_voi_sms.weekday_voi_roam_sec      ,
usg_dat_voi_sms.weekend_voi_roam_count    ,
usg_dat_voi_sms.weekend_voi_roam_sec   ,
uc.morning_voi_out_sec    ,
uc.afternoon_voi_out_sec  ,
uc.evening_voi_out_sec  ,
uc.night_voi_out_sec  ,
uc.peak_voi_out_sec  ,
uc.non_peak_voi_out_sec ,
cast(null  as bigint)   voi_volte_count,
cast(null  as double)  voi_volte_sec,
cast(null  as double)  call_drop_rate,
cast(null  as double)  call_success_rate
,sub.YearID ,sub.monthid,sub.WeekID ,sub.week_started  ,
sub.week_ended,
sub.tbl_dt
from cvm_db.cvm20_subs_tmp sub 
left join cvm_db.cvm20_usg_data_sms_voi_tmp usg_dat_voi_sms on sub.msisdn_key=usg_dat_voi_sms.msisdn_key and sub.tbl_dt=usg_dat_voi_sms.tbl_dt  
left join cvm_db.cvm20_customersubject_sn_tmp cs2 on sub.msisdn_key=cs2.msisdn_key and sub.tbl_dt=cs2.tbl_dt   
left join cvm_db.cvm20_usg_voi_usg_cluster_tmp uc on sub.msisdn_key=uc.msisdn_key and sub.tbl_dt=uc.tbl_dt  
left join cvm_db.CVM20_VOICE_SMS_INCOMING vsi on sub.msisdn_key=try_cast(vsi.msisdn_key as bigint) and sub.tbl_dt=vsi.tbl_dt 
where sub.dola <= 180
and sub.tbl_dt = yyyymmddRunDate;
commit;
