start transaction;
delete from flare_8.fb_cell_info_report_base where report_month=firstDayOfMonth; 
insert into flare_8.fb_cell_info_report_base
select  
		
		'NG' as country,
		site_id,
		gateway_id,
		ran,
		try_cast(ci as varchar) as ci,
		try_cast(lac as varchar) as lac,
		cgi,
		eci,
		try_cast(tac as varchar) as tac,
		tai,
		try_cast(enodeb_id as varchar) as enodeb_id,
		ecgi,
		status,
		frequency_mhz,
		tx_power_dbm,  
		operation_date, 
		cast(date_format(now(), '%Y-%m-%dT%h:%i:%s') as varchar) as date_time,
		date_format(now(),'%Y-%m-%dT%h:%i:%s') as date_key,		
		cell_year,
		missing_site_id,
		missing_cgi,
		incorrect_cgi,
		missing_ecgi,
		incorrect_ecgi,
		missing_tac,
		missing_lac,
		missing_frequency,
		missing_tx_power,
		mobile_site ,
		missing_operation_date,
		inactive_site,
		active_status,
		non_active_status,
		missing_from_site_info,
		not_in_maps,
		valid_record,
		0 as new_cell,
		firstDayOfMonth as report_month
from flare_8.vw_fb_cell_info_base_update
union all
select 
		'NG' as country,
		site_id,
		gateway_id,
		ran,
		ci,
		lac,
		cgi,
		cast(eci as varchar),
		tac,
		tai,
		enodeb_id,
		ecgi,
		status,
		frequency_mhz,
		tx_power_dbm,  
		operation_date,
		cast(date_format(now(), '%Y-%m-%dT%h:%i:%s') as varchar) as date_time,
		date_format(now(),'%Y-%m-%dT%h:%i:%s') as date_key,	
		cell_year,
		missing_site_id,
		missing_cgi,
		incorrect_cgi,
		missing_ecgi,
		incorrect_ecgi,
		missing_tac,
		missing_lac,
		missing_frequency,
		missing_tx_power,
		mobile_site ,
		missing_operation_date,
		inactive_site,
		active_status,
		non_active_status,
 		0 as missing_from_site_info,
		not_in_maps,
		valid_record,
		1 as new_cell,
		firstDayOfMonth as report_month
from flare_8.vw_fb_cell_info_new  ;
commit;
