start transaction;
delete from flare_8.fb_site_info_report_base where report_month=firstDayOfMonth;
insert into flare_8.fb_site_info_report_base
select
 'NG' as country,
 site_id,
 latitude_deg,
 longitude_deg,
 status,
 operation_date,
 active_ran_list,
 backhaul,
 capacity_uplink_kbps,
 capacity_downlink_kbps,
 fiber_date,
 site_type,
 cast(date_format(now(), '%Y-%m-%dT%h:%i:%s') as varchar) as date_time,
 date_format(now(),'%Y-%m-%dT%h:%i:%s') as date_key,	
 site_year,
 mobile_site,
 missing_site_id,
 missing_location,
 missing_backhaul,
 missing_capacity,
 missing_fibre_date,
 missing_operation_date,	
 missing_ran_list,
 missing_site_type,
 incorrect_status,
 missing_status,
 planned_status,
 active_status,
 inactive_status,
 decom_status,	
 valid_record,
 1 as new_site,
 firstDayOfMonth as report_month
from flare_8.vw_fb_site_info_new
union 
select
 'NG' as country,
 site_id,
 latitude_deg,
 longitude_deg,
 status,
 operation_date,
 active_ran_list,
 backhaul,
 capacity_uplink_kbps,
 capacity_downlink_kbps,
 fiber_date,
 site_type,
 cast(date_format(now(), '%Y-%m-%dT%h:%i:%s') as varchar) as date_time,
 date_format(now(),'%Y-%m-%dT%h:%i:%s') as date_key,
 site_year,
 mobile_site,
 missing_site_id,
 missing_location,
 missing_backhaul,
 missing_capacity,
 missing_fibre_date,
 missing_operation_date,	
 missing_ran_list,
 missing_site_type,
 incorrect_status,
 missing_status,
 planned_status,
 active_status,
 inactive_status,
 decom_status,	
 valid_record,	
 0 as new_site,
 firstDayOfMonth as report_month
from flare_8.fb_site_info_report_base
where report_month = firstDayOfpreviousMonth;

commit;
