start transaction;
delete from flare_8.fb_topology_map_dq_rpt where tbl_month >= firstDayOfpreviousMonth ; 
commit;
start transaction;
insert into flare_8.fb_topology_map_dq_rpt select tbl_dt,report_month,tbl_month_key,date_key,file_date,opco,feed_name,table_name,feed_frequency,file_received,file_received_rag,total_records,rejected_records,rejected_rag,average_7_days,average_7_days_rag,trend_rag,dq_issues,dq_rag,dq_percentage,duplicates,duplicate_rag,missing_site,missing_site_rag,missing_longitude,missing_longitude_rag,missing_latitude,missing_latitude_rag,missing_site_type,missing_site_type_rag,missing_uplink_kbps,missing_uplink_kbps_rag,missing_fibre_date,missing_fibre_date_rag,topology_map,source,tbl_month from flare_8.fb_topology_map_dq_rpt8 ;
commit;
