start transaction;
insert into engine_room.MFS_STOCK_LEVEL 
( select  z.original_timestamp_enrich, z.agentmsisdn, z.account_id,  z.wallet_type ,z.profile_category, z.EODBalance,z.kamanja_loaded_date, z.tbl_dt 
from 
( with agent_max_timestamp as ( select distinct (agentmsisdn) agentmsisdn, max(time_stamp) time_stamp , max(kamanja_loaded_date) kamanja_loaded_date ,tbl_dt,profile from( select distinct(msisdn_key)agentmsisdn, max(original_timestamp_enrich) time_stamp ,tbl_dt, instruct_from_fro_user_prf profile, max(kamanja_loaded_date) kamanja_loaded_date from flare_8.FINANCIAL_LOG where tbl_dt = yyyymmddRunDate and hdr_type = 'RESERVATION'and msisdn_key <>0 and substring(instruct_from_message, 1, 21) not in ('COMMISSIONLIQUIDATION') group by msisdn_key,tbl_dt,instruct_from_fro_user_prf union select distinct(try_cast(instruct_to_accnt_hldr_msisdn as bigint)) agentmsisdn, max(original_timestamp_enrich) time_stamp ,tbl_dt, instruct_to_fro_user_prf profile, max(kamanja_loaded_date) kamanja_loaded_date 
from flare_8.FINANCIAL_LOG 
where tbl_dt = yyyymmddRunDate and hdr_type = 'RESERVATION' and try_cast(instruct_to_accnt_hldr_msisdn as bigint) <>0 group by instruct_to_accnt_hldr_msisdn, tbl_dt,instruct_to_fro_user_prf )group by agentmsisdn, tbl_dt,profile ), agent_timestamp as (select * from ( select instruct_from_bal_tot_aft,  msisdn_key, instruct_from_fro_id account_id , original_timestamp_enrich  , kamanja_loaded_date, tbl_dt , row_number() OVER (PARTITION BY   original_timestamp_enrich   ORDER BY  instruct_hdr_fid  desc ) rnk 
from flare_8.FINANCIAL_LOG 
where tbl_dt = yyyymmddRunDate  and msisdn_key <>0 and hdr_type ='RESERVATION' and status_code='EXECUTED'  and instruct_hdr_type not in ('COMMISSIONING') union all select instruct_to_bal_tot_aft,  try_cast(instruct_to_accnt_hldr_msisdn as bigint), instruct_to_fro_id account_id, original_timestamp_enrich  , kamanja_loaded_date ,tbl_dt, row_number() OVER (PARTITION BY   original_timestamp_enrich   ORDER BY  instruct_hdr_fid  desc ) rnk from flare_8.FINANCIAL_LOG where tbl_dt = yyyymmddRunDate and status_code='EXECUTED'  and instruct_to_bal_tot_aft <>0 and instruct_from_accnt_hldr_msisdn in ('') and hdr_type = 'RESERVATION' and instruct_hdr_type in ('TRANSFER') ) where rnk = 1 ) select original_timestamp_enrich ,  agentmsisdn  , account_id  , wallet_type , profile_category , EODBalance ,kamanja_loaded_date ,  tbl_dt from ( select date_format(from_iso8601_timestamp(a.time_stamp ),'%Y%m%d%H%i%s') original_timestamp_enrich, cast(a.agentmsisdn as varchar) agentmsisdn, cast(account_id as varchar) account_id,  'main' wallet_type ,   lower(cc.rpt_category)  profile_category, b.instruct_from_bal_tot_aft EODBalance,     a.kamanja_loaded_date as kamanja_loaded_date, a.tbl_dt as tbl_dt, row_number() OVER (PARTITION BY  a.agentmsisdn  ORDER BY  a.time_stamp  desc ) rnk2 from agent_max_timestamp a left join agent_timestamp b on a.time_stamp=b.original_timestamp_enrich and a.agentmsisdn=b.msisdn_key and a.tbl_dt=b.tbl_dt 
left join 
nigeria.mfs_profile_categories cc 
on (a.profile = cc.profile_description ) )
where  rnk2 = 1) z)
;commit;
