start transaction;
insert into engine_room.POS_MSISDN 
select to_hex(sha1(to_utf8(pos_msisdn))) as msisdn_hash,pos_msisdn as msisdn,'mfs' as product_type,date_parse(date_format(now(),'%Y%m%d %H%i%s'),'%Y%m%d %H%i%s')  as update_datetime,tbl_dt from ( with pos_accounts as (select tbl_dt,   from_profile_category profile_category ,  sender_account_id accountid,  cast(sender_msisdn as varchar) pos_msisdn 
from 
engine_room.MFS_TRANSACTIONS 
where tbl_dt = yyyymmddRunDate and from_profile_category  in ('agent' , 'merchant') union all select tbl_dt,  to_profile_category profile_category ,  receiver_account_id  accountid,  cast(receiver_msisdn as varchar)  pos_msisdn 
from 
engine_room.MFS_TRANSACTIONS 
where tbl_dt = yyyymmddRunDate and to_profile_category  in ('agent' , 'merchant') ) select distinct tbl_dt, profile_category, accountid, pos_msisdn from pos_accounts ) union all select distinct to_hex(sha1(to_utf8(msisdn))) as msisdn_hash, msisdn, 'electronic_recharge' as product_type, date_parse(date_format(now(),'%Y%m%d %H%i%s'),'%Y%m%d %H%i%s')  as update_datetime,tbl_dt 
from 
( select coalesce (receivermsisdn,'') as msisdn , yyyymmddRunDate as tbl_dt from flare_8.ERS_VEND_NEW where tbl_dt =  yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_IN') and upper(resultstatus)='SUCCESS' UNION ALL select coalesce (sendermsisdn,'') as msisdn ,  yyyymmddRunDate as tbl_dt from flare_8.ERS_VEND_NEW where tbl_dt =  yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_OUT') and upper(resultstatus)='SUCCESS' UNION ALL select coalesce (sendermsisdn,'') as msisdn ,  yyyymmddRunDate as tbl_dt from flare_8.ERS_VEND_NEW where tbl_dt =  yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_THROUGH') and upper(resultstatus)='SUCCESS' UNION ALL select coalesce (receivermsisdn,'') as msisdn ,  yyyymmddRunDate as tbl_dt 
from flare_8.ERS_VEND_NEW 
where tbl_dt =  yyyymmddRunDate and case when upper(senderjuridicalname) in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile in ('IFS_TRANSFER') then 'SELL_IN' when upper(senderjuridicalname) not in ('MTN') and transactiontype in ('TRANSFER') and transactionprofile not in ('IFS_TRANSFER') then 'SELL_THROUGH' when transactiontype in ('TOPUP') then 'SELL_OUT' else 'OTHER' end in ('SELL_THROUGH') and upper(resultstatus)='SUCCESS' )
;commit;
