select
TRANSACTION_NUM_N
,STATUS_CHANGED_BY_N
,ITEM_CODE_N
,LOCATION_CODE_N
,UPLOAD_FILE_SEQUENCE_N
,SCHDL_LINK_CODE_N
,CURRENCY_VALUE_N
,IMSI_NUMBER_N
,LANGUAGE_CODE_N
,SEQ_NUM_N
,TO_CHAR(TRANSACTION_DATE_D, 'yyyymmdd hh24miss') TRANSACTION_DATE_D
,TO_CHAR(ACTIVATION_DATE_D, 'yyyymmdd hh24miss') ACTIVATION_DATE_D
,TO_CHAR(EXPIRY_DATE_D, 'yyyymmdd hh24miss') EXPIRY_DATE_D
,TO_CHAR(EXPIRED_DATE_D, 'yyyymmdd hh24miss') EXPIRED_DATE_D
,TO_CHAR(STATUS_CHANGE_DATE_D, 'yyyymmdd hh24miss') STATUS_CHANGE_DATE_D
,TO_CHAR(LAST_MODIFIED_DATE_D, 'yyyymmdd hh24miss') LAST_MODIFIED_DATE_D
,STATUS_V
,CONTRACT_TYPE_V
,STANDARD_DEPOSIT_FLG_V
,STND_DEPOSIT_COLLECTED_FLG_V
,GOLDEN_PACK_FLG_V
,STARTER_PACK_TYPE_V
,STATE_V
,PREACTIVATED_FLG_V
,PROFILE_CODE_V
,BPLAN_V
,SUBSIDIARY_CODE_V
,SDP_CODE_V
,DISTRIBUTOR_ID_V
,EPRO_V
,STARTER_PACK_SERIAL_NUM_V
,MOBILE_NUMBER_V
,SIM_NUMBER_V
,ICCID_V
,EXTERNAL_WAREHOUSE_V
,TRANSACTION_NUM_V
,IMEI_NUM_V
,SHIPPER_BOX_NUM_V
,TRANSPORT_BOX_NUM_V
,PALLET_NUM_V
,SIM_LOCATION_V
,KI_NUM_V
,SERVICE_TYPE_V
,PROV_RESPONSE_V
,PACKAGE_CODE_V
,OFFER_CODE_V
,DEALER_CODE_V
from CBS_APPS.GSM_STARTER_PACK_DTLS
WHERE  TRANSACTION_DATE_D >= TO_DATE('${DATE} 000000','YYYYMMDD HH24MISS') AND TRANSACTION_DATE_D <= TO_DATE('${DATE} 235959','YYYYMMDD HH24MISS')
