--Incremental load of CB SERV MAST. Apply incrementals of d-1 to base values of d-2 to create new base for d-1.
--New Partition Insert date=d-1; Base table date=d-2; Incrementals date=d-1;
--Example. At 12:05am on Jan4, 2019 you would update below to have new partition insert date 20190103. You will have two source feeds,
--one from base table flare_8.cb_serv_mast_view_live where tbl_dt=20190102 and the incremental from
--flare_8.cb_serv_mast_view_live_inc where tbl_dt=20190103.
--The dates below should reflect this logic and it will create a new partition rolling forward.
--Partition delete below should be that of d-1;
start transaction;
delete from flare_8.cb_serv_mast_view_live where tbl_dt=20190418 and msisdn_part =9;

insert into flare_8.cb_serv_mast_view_live
select
account_link_code_n,service_code_v,account_code_n,sub_service_code,status_code_v,subs_name_v,last_name_v,subs_title_v,package_code_v,
tariff_code_v,activation_date_d,erased_date_d,suspended_date_d,reactivation_date_d,mobl_num_voice_v,mobl_num_data_v,mobl_num_fax_v,
pre_terminate_date_d,contract_type_v,contract_start_d,contract_end_d,activated_by_user_code_n,registration_date_d,sim_num_v,
imsi_num_n,ic_number_v,x_directory_level_n,cable_type_n,additional_line_site_flg_v,additional_line_site_qty_n,geo_loc_zone_code_v,
sales_person_code_v,additional_sim_flag_v,additional_imsi_num_n,additional_sim_num_v,allow_marketing_calls_v,sevice_identifier_v,
bill_cycl_code_n,churn_flag_v,subscriber_category_v,subscriber_sub_category_v,preferred_language_v,hybrid_type_v,hybrid_service_status_v,
bc_tariff_change_type_v,commitment_amount_n,contact_number_v,date_of_birth,state_of_origin_v,lga_of_origin_v,mother_maiden_v,
print_zero_invoice_flg_v,date_d,msisdn_key,cast(20190418 as int) as tbl_dt,msisdn_part
from (
--Apply the ranking to the union all of the incremental of the current day and the base of prior day
select
src,
row_number() over (partition by msisdn_key order by account_link_code_n desc, date_d desc,tbl_dt desc) rnk,
account_link_code_n,
service_code_v,
account_code_n,
sub_service_code,
status_code_v,
subs_name_v,
last_name_v,
subs_title_v,
package_code_v,
tariff_code_v,
activation_date_d,
erased_date_d,
suspended_date_d,
reactivation_date_d,
mobl_num_voice_v,
mobl_num_data_v,
mobl_num_fax_v,
pre_terminate_date_d,
contract_type_v,
contract_start_d,
contract_end_d,
activated_by_user_code_n,
registration_date_d,
sim_num_v,
imsi_num_n,
ic_number_v,
x_directory_level_n,
cable_type_n,
additional_line_site_flg_v,
additional_line_site_qty_n,
geo_loc_zone_code_v,
sales_person_code_v,
additional_sim_flag_v,
additional_imsi_num_n,
additional_sim_num_v,
allow_marketing_calls_v,
sevice_identifier_v,
bill_cycl_code_n,
churn_flag_v,
subscriber_category_v,
subscriber_sub_category_v,
preferred_language_v,
hybrid_type_v,
hybrid_service_status_v,
bc_tariff_change_type_v,
commitment_amount_n,
contact_number_v,
date_of_birth,
state_of_origin_v,
lga_of_origin_v,
mother_maiden_v,
print_zero_invoice_flg_v,
date_d,
msisdn_key,
tbl_dt,
msisdn_part
from (
--Incrementals of the day to be applied
select
'incr' src,
account_link_code_n,
service_code_v,
account_code_n,
sub_service_code,
status_code_v,
subs_name_v,
last_name_v,
subs_title_v,
package_code_v,
tariff_code_v,
activation_date_d,
erased_date_d,
suspended_date_d,
reactivation_date_d,
mobl_num_voice_v,
mobl_num_data_v,
mobl_num_fax_v,
pre_terminate_date_d,
contract_type_v,
contract_start_d,
contract_end_d,
activated_by_user_code_n,
registration_date_d,
sim_num_v,
imsi_num_n,
ic_number_v,
x_directory_level_n,
cable_type_n,
additional_line_site_flg_v,
additional_line_site_qty_n,
geo_loc_zone_code_v,
sales_person_code_v,
additional_sim_flag_v,
additional_imsi_num_n,
additional_sim_num_v,
allow_marketing_calls_v,
sevice_identifier_v,
bill_cycl_code_n,
churn_flag_v,
subscriber_category_v,
subscriber_sub_category_v,
preferred_language_v,
hybrid_type_v,
hybrid_service_status_v,
bc_tariff_change_type_v,
commitment_amount_n,
contact_number_v,
date_of_birth,
state_of_origin_v,
lga_of_origin_v,
mother_maiden_v,
print_zero_invoice_flg_v,
date_d,
msisdn_key,
tbl_dt,
msisdn_part
from flare_8.cb_serv_mast_view_live_inc where tbl_dt=20190418 and msisdn_part =9
union all
--Base table of prior day to bring across
select
'base' src,
account_link_code_n,
service_code_v,
account_code_n,
sub_service_code,
status_code_v,
subs_name_v,
last_name_v,
subs_title_v,
package_code_v,
tariff_code_v,
activation_date_d,
erased_date_d,
suspended_date_d,
reactivation_date_d,
mobl_num_voice_v,
mobl_num_data_v,
mobl_num_fax_v,
pre_terminate_date_d,
contract_type_v,
contract_start_d,
contract_end_d,
activated_by_user_code_n,
registration_date_d,
sim_num_v,
imsi_num_n,
ic_number_v,
x_directory_level_n,
cable_type_n,
additional_line_site_flg_v,
additional_line_site_qty_n,
geo_loc_zone_code_v,
sales_person_code_v,
additional_sim_flag_v,
additional_imsi_num_n,
additional_sim_num_v,
allow_marketing_calls_v,
sevice_identifier_v,
bill_cycl_code_n,
churn_flag_v,
subscriber_category_v,
subscriber_sub_category_v,
preferred_language_v,
hybrid_type_v,
hybrid_service_status_v,
bc_tariff_change_type_v,
commitment_amount_n,
contact_number_v,
date_of_birth,
state_of_origin_v,
lga_of_origin_v,
mother_maiden_v,
print_zero_invoice_flg_v,
date_d,
msisdn_key,
tbl_dt,
msisdn_part
from flare_8.cb_serv_mast_view_live where tbl_dt=cast(date_format(date_add('day',-1,date_parse(cast(20190418 as varchar),'%Y%m%d')),'%Y%m%d') as int) and msisdn_part =9
) 
) where rnk=1;
commit;
