#!/bin/bash

date=$1

mytime() {
date +"%Y-%m-%d_%H-%M-%S"
}

time java -Xmx30g -Xms30g -Dlog4j.configurationFile=/home/daasuser/fileOps/log4j2.xml -jar /home/daasuser/fileOps/FileOps_2.11-0.1-SNAPSHOT_index.jar -in /mnt/beegfs/share/production/archived/AIR_ADJ_DA/$date /mnt/beegfs/share/production/archived/AIR_REFILL_MA/$date /mnt/beegfs/share/production/archived/CCN_GPRS_DA/$date /mnt/beegfs/share/production/archived/CCN_SMS_MA/$date /mnt/beegfs/share/production/archived/GGSN/$date /mnt/beegfs/share/production/archived/MSC/$date /mnt/beegfs/share/production/archived/SDP_ADJ_DA/$date /mnt/beegfs/share/production/archived/AIR_ADJ_MA/$date /mnt/beegfs/share/production/archived/BUNDLE4U_GPRS/$date /mnt/beegfs/share/production/archived/CCN_GPRS_MA/$date /mnt/beegfs/share/production/archived/CCN_VOICE_AC/$date /mnt/beegfs/share/production/archived/HSDP/$date /mnt/beegfs/share/production/archived/SDP_DMP_MA/$date /mnt/beegfs/share/production/archived/AIR_REFILL_AC/$date /mnt/beegfs/share/production/archived/BUNDLE4U_VOICE/$date /mnt/beegfs/share/production/archived/CCN_SMS_AC/$date /mnt/beegfs/share/production/archived/CCN_VOICE_DA/$date /mnt/beegfs/share/production/archived/DMC_DUMP_ALL/$date /mnt/beegfs/share/production/archived/MAPS_INV_2G/$date /mnt/beegfs/share/production/archived/SDP_ACC_ADJ_AC/$date /mnt/beegfs/share/production/archived/SGSN/$date /mnt/beegfs/share/production/archived/AIR_REFILL_DA/$date /mnt/beegfs/share/production/archived/CCN_GPRS_AC/$date /mnt/beegfs/share/production/archived/CCN_SMS_DA/$date /mnt/beegfs/share/production/archived/CCN_VOICE_MA/$date /mnt/beegfs/share/production/archived/EWP_FINANCIAL_LOG/$date /mnt/beegfs/share/production/archived/MAPS_INV_4G/$date /mnt/beegfs/share/production/archived/SDP_ACC_ADJ_MA/$date /mnt/beegfs/share/production/archived/WBS_PM_RATED_CDRS/$date /mnt/beegfs/share/production/archived/SDP_DMP_AC/$date  /mnt/beegfs/share/production/archived/SDP_DMP_DA/$date /mnt/beegfs/share/production/archived/SDP_DUMP_OFFER/$date /mnt/beegfs/share/production/archived/SDP_DUMP_SUBSCRIBER/$date  -out /mnt/beegfs/share/tmp/waddah/linecount_withindex -od -tf 10 -nt 32 -dp 15 -of -op lineCount -lbl lineCount_withindex$date -lcwi /mnt/beegfs/share/tmp/waddah/index_linecount -fnfp 6 -rg "^.{0,8}" 2>&1 | tee "/mnt/beegfs/share/tmp/waddah/linecount_withindex/linecount_withindex_archived_$date_$(mytime).log"
