select 
USER_ID ,
FULL_NAME ,
RETAIL_SHOP ,
CUSTOMER_NO ,
CUSTOMER_NAME ,
STATE ,
STATE_CODE ,
RETAIL_SHOP_NO ,
SHOP_DESCRIPTION ,
REGION_CODE ,
REGION_DESCRIPTION
from ifsapp.mtn_connect_user_details
