SELECT TO_CHAR(TRUNC(SYSDATE) -1 , 'yyyymmdd hh24miss') SNAPSHOT,
       GET_EMAIL,
       AGENT_FIRST_NAME,
       AGENT_SURNAME,
       AGENT_MOBILE,
       DEALER_NAME,
       DEALER_CODE,
       DEALER_MOBILE,
       DEAL_ADDRESS
  FROM BIOCAPTURE.AGENT_USER_BIB
