
beeline -n daasuser -p '' -u 'jdbc:hive2://datanode01026.mtn.com:2181,datanode01028.mtn.com:2181,master01001.mtn.com:2181,master01002.mtn.com:2181,master01003.mtn.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2' -e "msck repair table flare_8.ngvs_cdr;
 msck repair table flare_8.AVAYA_CLID;
 msck repair table flare_8.AVAYA_IVR;
 msck repair table flare_8.cs5_vtu_dump;
 msck repair table flare_8.NGVS_CDR;
 msck repair table flare_8.CIS_CDR;
 msck repair table flare_8.msc_daas;
 msck repair table flare_8.TAPIN_VOICE;
 msck repair table flare_8.TAPOUT_VOICE;
 msck repair table flare_8.TAPIN_GPRS;
 msck repair table flare_8.TAPOUT_GPRS;
 msck repair table flare_8.FLYTXT_CAMPAIGN_EVENTS_DATA_new;
 msck repair table flare_8.FLYTXT_CAMPAIGN_EVENTS_DATA;
 msck repair table flare_8.offer_dump;
 msck repair table flare_8.LEA_MAPPING_MSC_DAAS;
 msck repair table flare_8.file_stats;
 msck repair table flare_8.landingzonerecon;
 msck repair table flare_8.cs5_sdp_pam_all;
 msck repair table flare_8.HSDP_DOI_LOG;
 msck repair table flare_8.MVAS_DND_MSISDN_REPORT;
 msck repair table flare_8.ESM_PMT_METRIC;
 msck repair table flare_8.ESM_REFILL_METRIC;
 msck repair table flare_8.MA_MONITOR;
 msck repair table flare_8.MAPS_2G_CELL_D;
 msck repair table flare_8.MAPS_3G_CELL_D;
 msck repair table flare_8.MAPS_3G_CN_D;
 msck repair table flare_8.MAPS_3G_CN_D_BH;
 msck repair table flare_8.MNP_LOCATION;
 msck repair table flare_8.MNP;
 msck repair table flare_8.CLM_WBO;
 msck repair table flare_8.agl_gds_provider_child_dtls;
 msck repair table flare_8.all_stmt_account_open_inv_vw;
 msck repair table flare_8.clawback_rpt;
 msck repair table flare_8.all_stmt_service_open_cred_vw;
 msck repair table flare_8.all_stmt_service_open_debt_vw;
 msck repair table flare_8.cug_access_fee_base_vw;
 msck repair table flare_8.excess_payment_rpt;
 msck repair table flare_8.mso_bib_payment_reversal_vw;
 msck repair table flare_8.bulk_sms;
 msck repair table flare_8.MYMTNWEB_ACTIVEUSERS;
 msck repair table flare_8.Mso_post_eyeballing_vw;
 msck repair table flare_8.Ussd_charging_cdr;
 msck repair table flare_8.Stat_bill_ussd;
 msck repair table flare_8.smsc;
 msck repair table flare_8.mymtnweb_plugin_cdr;
 msck repair table flare_8.mymtnweb_activeusers;
 msck repair table flare_8.smart_app_cdr;
 msck repair table flare_8.smart_app_new_users;
 msck repair table flare_8.smart_app_new_download;
 msck repair table flare_8.agent_registration;
 msck repair table flare_8.DIGITAL_INSURANCE_REGISTERATIONS;
 msck repair table flare_8.DIGITAL_INSURANCE_CUSTOMERS;
 msck repair table flare_8.DIGITAL_INSURANCE_TRANSACTIONS;"
 
 beeline -n daasuser -p '' -u 'jdbc:hive2://datanode01026.mtn.com:2181,datanode01028.mtn.com:2181,master01001.mtn.com:2181,master01002.mtn.com:2181,master01003.mtn.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2' -e " msck repair table flare_8.ABLT_GSM_STARTER_PACK
 ;msck repair table flare_8.mso_post_swap_eyeballing_vw
 ;msck repair table flare_8.edw_sim_swap
 ;msck repair table flare_8.call_reason
 ;msck repair table flare_8.edw_report
 ;msck repair table flare_8.mtn_fast_eyeballing_rpt
 ;msck repair table flare_8.sip_server
 ;msck repair table flare_8.flutterwave_isec
 ;msck repair table flare_8.QRIOS_SDP_TIMEOUT
 ;msck repair table flare_8.TEMP_PERM_CRDLMT_CHANGE_VW
 ;msck repair table FLARE_8.SMD_IDENTITIES
 ;msck repair table FLARE_8.SMD_PRESENCE_TIME
 ;msck repair table FLARE_8.SMD_AGENTS_NOTIFICATIONS
 ;msck repair table FLARE_8.SMD_MESSAGES
 ;msck repair table FLARE_8.SMD_SOURCES
 ;msck repair table FLARE_8.SMD_AGENTS
 ;msck repair table FLARE_8.SMD_INTERVENTIONS
 ;msck repair table FLARE_8.HYNETFLEX_CUSTOMER
 ;msck repair table FLARE_8.CB_MNP_INTERFACE_DTLS
 ;msck repair table FLARE_8.STAFF_OIM_EXTRACT
 ;msck repair table FLARE_8.CB_ACCOUNT_SERVICE_LIST
 ;msck repair table FLARE_8.CB_POS_EXCL_INCL_HIST
 ;msck repair table FLARE_8.SERVICE_PROVIDER_LOG
 ;msck repair table FLARE_8.MTNAPPNXG_NEW_DAILY_USERS
 ;msck repair table FLARE_8.SM_CHARGING_ERROR_CDR
 ;msck repair table FLARE_8.SM_CHARGING_SUCCESS_CDR
 ;msck repair table FLARE_8.SM_DND_CDR
 ;msck repair table FLARE_8.SM_DOI_CDR
 ;msck repair table FLARE_8.BEMOBI_TRANSACTIONS
 ;msck repair table FLARE_8.BEMOBI_STATISTICS
 ;msck repair table FLARE_8.CELL_INFO_2G 
 ;msck repair table FLARE_8.CELL_INFO_3G 
 ;msck repair table FLARE_8.CELL_INFO_4G 
 ;msck repair table FLARE_8.CELL_QOS_2G 
 ;msck repair table FLARE_8.CELL_QOS_3G 
 ;msck repair table FLARE_8.CELL_QOS_4G 
 ;msck repair table FLARE_8.MAPS_SITE_INFO 
 ;msck repair table FLARE_8.TOPOLOGY_MAP  
 ;msck repair table FLARE_8.MTN_NG_3G_DAILY 
 ;msck repair table FLARE_8.MTN_NG_4G_DAILY 
 ;msck repair table FLARE_8.MTN_NG_3G_MONTHLY 
 ;msck repair table FLARE_8.MTN_NG_4G_MONTHLY 
 ;msck repair table FLARE_8.MTNN_ASSET_EXTRACT_2G_CELLS 
 ;msck repair table FLARE_8.MTNN_ASSET_EXTRACT_3G_CELLS 
 ;msck repair table FLARE_8.MTNN_ASSET_EXTRACT_4G_CELLS 
 ;msck repair table FLARE_8.POPULATION_DS
 ;msck repair table FLARE_8.MTN_NG_GATEWAY_INFORMATION"

