SELECT /*+ parallel(10) */
       RECORD_ID,
       CUSTOMER_NAME,
       UNIQUE_ID,
       TRIM(LEADING 0 FROM TRIM(PHONE_NUMBER)) PHONE_NUMBER,
       CAPTURE_VERSION,
       TO_CHAR(RECEIPT_TIMESTAMP, 'yyyymmddhh24miss')
  FROM BIOCAPTURE.VALIDATION_PASSED
 WHERE TRUNC(RECEIPT_TIMESTAMP) >= TO_DATE('${DATE}', 'yyyymmdd')
   AND TRUNC(RECEIPT_TIMESTAMP) < TO_DATE('${DATE}', 'yyyymmdd')+1