SELECT /*+ parallel(10)*/
    LOGIN_ID_V,
    PASSWORD_V,
    SERV_ACC_LINK_CODE_N,
    STATUS_V,
    TRANSACTION_NUM_V,
    TO_CHAR(TRANS_DATE_D AT TIME ZONE 'Africa/Algiers', 'yyyymmdd hh24miss') TRANS_DATE_D,
    ITEM_CODE_N,
    LOCATION_CODE_N,
    SERVICE_CODE_V,
    SUB_SERVICE_CODE_V,
    DUMMY_NUMBER_V
 FROM TT_MSO_1.ISP_LOGIN_IDS_LOOKUP
 WHERE TRUNC(TRANS_DATE_D AT TIME ZONE 'Africa/Algiers') = TRUNC(TO_DATE('${DATE}', 'yyyymmdd'))
