#!/bin/bash
KAMANJA_HOME=/home/daasuser/Kamanja_test
METADATA_LOCATION=/home/daasuser/Kamanja_test_metadata_with_uniqueKey/output/CUST_ORD_CUSTOMER_ENT/
TYPES=(all)
TENANT_ID=tenant1
DATA_PATH=
DATA_NAMESPACE=
Usage(){ echo "Usage: [ --types ( messages|hql|configs|models|bindings|all ) ] [--hiveDataPath] [--hiveDataNameSpace] [ --tenantId  ] [ --kamanja_home ] [ --metadata_location ]";}
while [ $# -gt 1 ]
	do
	case $1 in 
	--tenantId)
	TENANT_ID=$2
	shift
	;;
	--types)
	TYPES=(${2//,/ })
	shift
	;;
	--hiveDataNameSpace)
	DATA_NAMESPACE=$2
	shift
	;;
	--kamanja_home)
	KAMANJA_HOME=$2
	shift
	;;
	--hiveDataPath)
	DATA_PATH=$2
	shift
	;;
	--metadata_location)
	METADATA_LOCATION=$2
	shift
	;;
	*)
	Usage;exit -1
	shift
	;;
	esac
	shift
done
for t in ${TYPES[@]};do
case $t in messages|hql|configs|models|bindings|all);; *) Usage;exit -1;; esac
if [ "${t}" == "messages" ] || [ "${t}" == "all" ];then
echo adding messages
$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $METADATA_LOCATION/CUST_ORD_CUSTOMER_ENT_input.json TENANTID ${TENANT_ID}
$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add message $METADATA_LOCATION/CUST_ORD_CUSTOMER_ENT_msg.json TENANTID ${TENANT_ID}
fi
if [ "${t}" == "hql" ] || [ "${t}" == "all" ];then
echo creating hive tables
 hive  -hivevar DATA_NAMESPACE=${DATA_NAMESPACE} -hivevar DATA_PATH=${DATA_PATH} -f $METADATA_LOCATION/CUST_ORD_CUSTOMER_ENT.hql
fi
if [ "${t}" == "configs" ] || [ "${t}" == "all" ];then
echo uploading compile config
$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties upload compile config $METADATA_LOCATION/CUST_ORD_CUSTOMER_ENT_ModelCompileConfig.json
fi
if [ "${t}" == "models" ] || [ "${t}" == "all" ];then
echo adding models
$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add model jtm   $METADATA_LOCATION/CUST_ORD_CUSTOMER_ENT_schema.jtm DEPENDSON CUST_ORD_CUSTOMER_ENT TENANTID ${TENANT_ID}
fi
if [ "${t}" == "bindings" ] || [ "${t}" == "all" ];then
echo adding adapter bindings
$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add adaptermessagebinding FROMFILE  $METADATA_LOCATION/Binding.hdfs_output_adapter_1_CUST_ORD_CUSTOMER_ENT.json
fi
done
