SELECT /*+ parallel(20)*/
DISTINCT TRIM(LEADING 0 FROM TRIM(S.PHONE_NUMBER)) PHONE_NUMBER,
         S.UNIQUE_ID,
         TO_CHAR(S.REGISTRATION_TIMESTAMP, 'yyyymmddhh24miss'),
         TO_CHAR(S.RECEIPT_TIMESTAMP, 'yyyymmddhh24miss'),
         TO_CHAR(S.CONFIRMATION_TIMESTAMP, 'yyyymmddhh24miss'),
         S.REGISTRATION_TYPE,
         TO_CHAR(BB.FILE_SYNC_DATE, 'yyyymmddhh24miss'),
         SS.NAME AS STATE,
         BB.TARGET_PATH,
         (CASE WHEN DA14 = 'UNVERIFIED' THEN 'OFFLINE' ELSE 'ONLINE' END) AS STATUS
  FROM BIOCAPTURE.SMS_ACTIVATION_REQUEST S,
       BIOCAPTURE.BID_VIEW               B,
       BIOCAPTURE.META_DATA              M,
       BIOCAPTURE.BFP_SYNC_LOG           BB,
       BIOCAPTURE.DYNAMIC_DATA           D,
       BIOCAPTURE.STATE                  SS
 WHERE S.UNIQUE_ID = BB.UNIQUE_ID
   AND BB.UNIQUE_ID = B.UNIQUE_ID
   AND B.ID = M.BASIC_DATA_FK
   AND D.BASIC_DATA_FK = B.ID
   AND SS.ID = S.STATE_ID
   AND TRUNC(RECEIPT_TIMESTAMP) >= TRUNC(TO_DATE('${DATE}', 'yyyymmdd'))
      AND TRUNC(RECEIPT_TIMESTAMP) < TRUNC(TO_DATE('${DATE}', 'yyyymmdd')) + 1
    
   