SELECT /*+ parallel(6) */
 TO_CHAR(REF_DATE, 'yyyymmdd hh24miss') REF_DATE,
 RETAIL_SHOP_NO,
 SHOP_NAME,
 USER_ID,
 DAY_TRANS_NO,
 PART_NO,
 PART_CATEGORY,
 PAY_TYPE_ID,
 GROSS_PRICE,
 INV_DESC
  FROM IFSAPP.SERVICE_CONNECT_STORE
 WHERE REF_DATE = TO_DATE('${DATE}', 'yyyyMMdd')

