 SELECT /*+ parallel(10)*/
 PHONE_NUMBER,
 TO_CHAR(RECEIPT_TIMESTAMP, 'yyyymmdd hh24miss'),
 TO_CHAR(REGISTRATION_TIMESTAMP, 'yyyymmdd hh24miss'),
 STATE_ID,
 STATUS,
 UNIQUE_ID, 
 REGISTRATION_TYPE,
 TO_CHAR(CONFIRMATION_TIMESTAMP, 'yyyymmdd hh24miss'),
 TO_CHAR(FILE_SYNC_DATE, 'yyyymmdd hh24miss'),                           
 TRIM(LEADING 0 FROM TRIM(PHONE_NUMBER)),
 TO_CHAR(RECEIPT_TIMESTAMP, 'yyyymmdd')
 FROM BIOCAPTURE.SMS_ACTIVATION_VW S
 WHERE TRUNC(RECEIPT_TIMESTAMP) >= TO_DATE('${DATE}', 'yyyymmdd')
   AND TRUNC(RECEIPT_TIMESTAMP) < TO_DATE('${DATE}', 'yyyymmdd') + 1
