select
CUSTOMER_ID
,NAME
,TO_CHAR(CREATION_DATE,'YYYY-MM-DD HH24:MI:SS')
,ASSOCIATION_NO
,PARTY
,DEFAULT_DOMAIN
,DEFAULT_LANGUAGE
,DEFAULT_LANGUAGE_DB
,COUNTRY
,COUNTRY_DB
,PARTY_TYPE
,PARTY_TYPE_DB
,CORPORATE_FORM
,IDENTIFIER_REFERENCE
,IDENTIFIER_REF_VALIDATION
,IDENTIFIER_REF_VALIDATION_DB
,TEXT_ID$
,PICTURE_ID
,OBJID
,OBJVERSION
from IFSAPP.CUSTOMER_INFO
