SELECT /*+ parallel(4)*/
  TO_CHAR(REF_DATE,'yyyymmdd hh24miss') REF_DATE,
  RETAIL_SHOP_NO,
  TRANSLATE(TRANSLATE(TRANSLATE(SHOP_NAME, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') SHOP_NAME,
  TRANSLATE(TRANSLATE(TRANSLATE(USER_ID, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') USER_ID,
  DAY_TRANS_NO,
  TRANSLATE(TRANSLATE(TRANSLATE(PART_NO, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') PART_NO,
  TRANSLATE(TRANSLATE(TRANSLATE(PART_CATEGORY, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') PART_CATEGORY,
  TRANSLATE(TRANSLATE(TRANSLATE(PAY_TYPE_ID, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') PAY_TYPE_ID,
  GROSS_PRICE,
  TRANSLATE(TRANSLATE(TRANSLATE(INV_DESC, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') INV_DESC
FROM IFSAPP.SERVICE_CENTRE_SALES
WHERE TRUNC(REF_DATE) >= TO_DATE('${DATE}','yyyymmdd')
      AND TRUNC(REF_DATE) < TO_DATE('${DATE}','yyyymmdd') + 1
