SELECT
 SUBSCRIBER_CODE_N,    
 ACCOUNT_CODE_N,       
 ACCOUNT_NAME_V,       
 SERVICE_INFO_V,       
 STATUS_CODE_V,        
 ACCOUNT_LINK_CODE_N,  
 OFFER_CODE_V,         
 SCHEME_REF_CODE_N,    
 CUG_OFFER_ADDED_DATE, 
 SCHEME_TYPE_V,        
 STATUS_OPTN_V,        
 COMMUNITY_ID,         
 PAM_ID,               
 CUG_VALUE  
FROM  TT_MSO_1.CUG_ACCESS_FEE_BASE_VW
