Select
case  when PROFILE_NAME LIKE '%'||chr(124)||'%' then
'"' || translate(REPLACE(PROFILE_NAME,'"',''''), chr(10)||chr(11)||chr(13) , ' ')  || '"'
else translate(REPLACE(PROFILE_NAME,'"',''''), chr(10)||chr(11)||chr(13) , ' ') end as PROFILE_NAME,
PROFILE_CODE,
'"' || translate(PROFILE_TYPE, chr(10)||chr(11)||chr(13) , ' ') || '"',
case  when INVOICE_ACCOUNT_NAME LIKE '%'||chr(124)||'%' then
'"' || translate(REPLACE(INVOICE_ACCOUNT_NAME,'"',''''), chr(10)||chr(11)||chr(13) , ' ')  || '"'
else translate(REPLACE(INVOICE_ACCOUNT_NAME,'"',''''), chr(10)||chr(11)||chr(13) , ' ') end as INVOICE_ACCOUNT_NAME,
INVOICE_ACCOUNT_CODE,
SERVICE_ACCOUNT_LINK_CODE,
'"' || translate(OLD_ACCOUNT_CODE , chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(SERVICE_ID, chr(10)||chr(11)||chr(13) , ' ')  || '"',
'"' || translate(SERVICE_NAME, chr(10)||chr(11)||chr(13) , ' ')  || '"',
'"' || translate(SUBSCRIBER_CATEGORY, chr(10)||chr(11)||chr(13) , ' ')  || '"',
'"' || translate(SUBSCRIBER_SUB_CATEGORY, chr(10)||chr(11)||chr(13) , ' ')  || '"',
'"' || translate(BUSINESS_TYPE, chr(10)||chr(11)||chr(13) , ' ')  || '"',
'"' || translate(PACKAGE_NAME, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(SERVICE_STATUS, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(ACCOUNT_MANAGER, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(LINK_DESCRIPTION, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(UPLINK_SPEED, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(DOWNLINK_SPEED, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(IP_BANDWIDTH, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(SOFT_SUSPENDED, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(STATUS_DATE, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(START_DATE, chr(10)||chr(11)||chr(13) , ' ') || '"' ,
'"' || translate(NO_CHARGE_FLAG, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(PRODUCT, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(SERVICE, chr(10)||chr(11)||chr(13) , ' ') || '"',
'"' || translate(TAX_PLAN, chr(10)||chr(11)||chr(13) , ' ') || '"',
translate(UNBILLED_USAGE , chr(10)||chr(11)||chr(13) , ' '),
'"' || translate(BILL_CYCLE , chr(10)||chr(11)||chr(13) , ' ') || '"',
translate(CREDIT_LIMIT, chr(10)||chr(11)||chr(13) , ' ') ,
translate(RENTALS , chr(10)||chr(11)||chr(13) , ' ') ,
translate(ADVANCE_PAID, chr(10)||chr(11)||chr(13) , ' ') ,
translate(OUTSTANDING_BALANCE, chr(10)||chr(11)||chr(13) , ' ') ,
translate(CURRENT_BALANCE , chr(10)||chr(11)||chr(13) , ' '),
'"' || translate(CONTACT_PHONE_NUMBER, chr(10)||chr(11)||chr(13) , ' ') || '"',
translate(EMAIL_ADDRESS, chr(10)||chr(11)||chr(13) , ' ') ,
CONTACT_PERSON,TARIFF_CODE ,ACTIVATION_DATE_D ,SUSPENDED_DATE_D ,
PRE_TERMINATE_DATE_D ,REGISTRATION_DATE_D ,PROFILE_CREATION_DATE,ACCOUNT_CREATION_DATE ,CUST_SUPPORT_MANAGER,JOB_ORDER_CREATED_DT ,
JOB_ORDER_CLOSED_DT ,NON_RECURRING_CHARGE,NOMINATED_TM_MSISDN ,REGISTERED_MSISDN , PIN_REF_NUM  ,TM_CASCADE_FLG
FROM TT_MSO_1.BIB_AGL_GSM_STS_REPORT