SELECT '234' || EXTRACTVALUE(REQUEST_OBJECT_X, '/EVENT/MNPDETAILS/NUMBERS[1]/STARTNUMBER') || '|' ||
       EXTRACTVALUE(REQUEST_OBJECT_X, '/EVENT/REQUESTDETAILS/@DONOR_NAME') || '|' ||
       'MTN' || '|' || 
       TO_CHAR(ACTION_DATE_DT, 'yyyy-mm-dd hh24:mi:ss') || '|' ||
       TO_CHAR(ACTION_DATE_DT, 'yyyymmdd')
  FROM CBS_TBL_CUST.CB_MNP_INTERFACE_API_LOG
 WHERE OPERATION_NAME_V = '1010'
   AND STATUS_V IN ('C', 'P')
   AND ACTION_DATE_DT >= TO_DATE('${date} 00:00:00', 'yyyymmdd hh24:mi:ss')
   AND ACTION_DATE_DT <= TO_DATE('${WEEK} 23:59:59', 'yyyymmdd hh24:mi:ss')
UNION ALL
SELECT '234' || EXTRACTVALUE(REQUEST_OBJECT_X, '/EVENT/MNPDETAILS/NUMBERS[1]/STARTNUMBER') || '|' ||
       'MTN' || '|' || 
       SUBSTR(EXTRACTVALUE(REQUEST_OBJECT_X,'/EVENT/REQUEST/@REQUEST_IDENTIFIER'),15,3) || '|' ||
       TO_CHAR(ACTION_DATE_DT, 'yyyy-mm-dd hh24:mi:ss') || '|' ||
       TO_CHAR(ACTION_DATE_DT, 'yyyymmdd')
  FROM CBS_TBL_CUST.CB_MNP_INTERFACE_API_LOG
 WHERE OPERATION_NAME_V = '1009'
   AND STATUS_V IN ('C', 'P')
   AND ACTION_DATE_DT >= TO_DATE('${date} 00:00:00', 'yyyymmdd hh24:mi:ss')
   AND ACTION_DATE_DT <= TO_DATE('${WEEK} 23:59:59', 'yyyymmdd hh24:mi:ss')
