SELECT '234' || A.MOBILE_NUMBER_V || '|' ||
       EXTRACTVALUE(REQUEST_OBJECT_X, '/EVENT/REQUESTDETAILS/@DONOR_NAME') || '|' ||
       'MTN' || '|' ||
       TO_CHAR(DATE_DT, 'yyyy-mm-dd hh24:mi:ss') || '|' ||
	    to_char(DATE_DT,'yyyymmdd')
  FROM CBS_TBL_CUST.CB_MNP_INTERFACE_DTLS A,
       CBS_TBL_CUST.CB_MNP_AUDIT_LOG      B
 WHERE A.OPERATION_NAME_V IN ('1010', '1005')
   AND A.TRANSACTION_NUM_N = B.TRANSACTION_NUM_N
   AND B.OPERATION_NAME_V = '1000'
   AND A.MOBILE_NUMBER_V = B.MOBILE_NUMBER_V
   AND A.STATUS_V IN ('C', 'P')
   AND ACTION_DATE_DT >=
       TO_DATE('${date} 00:00:00', 'yyyymmdd hh24:mi:ss')
   AND ACTION_DATE_DT <=TO_DATE('${date} 23:59:59', 'yyyymmdd hh24:mi:ss')
UNION ALL
SELECT '234' || B.MOBILE_NUMBER_V || '|' ||
 'MTN' || '|' ||
       SUBSTR(EXTRACTVALUE(REQUEST_OBJECT_X,'/EVENT/REQUEST/@REQUEST_IDENTIFIER'),15,3) || '|' ||
       TO_CHAR(ACTION_DATE_DT, 'yyyy-mm-dd hh24:mi:ss') || '|' ||
	   to_char(ACTION_DATE_DT,'yyyymmdd')
  FROM CBS_TBL_CUST.CB_MNP_AUDIT_LOG A, CBS_TBL_CUST.CB_MNP_INTERFACE_DTLS B
 WHERE A.OPERATION_NAME_V = '1009'
   AND B.STATUS_V = 'C'
   AND A.TRANSACTION_NUM_N = B.TRANSACTION_NUM_N
   AND A.ACTION_DATE_DT >=
       TO_DATE('${date} 00:00:00', 'yyyymmdd hh24:mi:ss')
   AND A.ACTION_DATE_DT <=TO_DATE('${date} 23:59:59', 'yyyymmdd hh24:mi:ss')
