SELECT /*+ parallel(4)*/
 TRANSLATE(TRANSLATE(TRANSLATE(SITE, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') SITE,
 TRANSLATE(TRANSLATE(TRANSLATE(LOCATION_NO, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') LOCATION_NO,
 TO_CHAR(DATED,'yyyymmdd hh24miss') DATED,
 TRANSLATE(TRANSLATE(TRANSLATE(TRANSACTION_CODE, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') TRANSACTION_CODE,
 TRANSLATE(TRANSLATE(TRANSLATE(TRANSACTION_TYPE, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') TRANSACTION_TYPE,
 TRANSLATE(TRANSLATE(TRANSLATE(PART_NO, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') PART_NO,
 TRANSLATE(TRANSLATE(TRANSLATE(ORDER_NO, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') ORDER_NO,
 TRANSLATE(TRANSLATE(TRANSLATE(DESCRIPTION, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') DESCRIPTION,
 TRANSLATE(TRANSLATE(TRANSLATE(ASSET_CLASS, CHR(10), ' '), CHR(13), ' '), CHR(09), ' ') ASSET_CLASS,
 SALES_QUANTITY,
 SALES_VALUE,
 SALES_COST
 FROM IFSAPP.IFS_SALES_HIST
 WHERE TRUNC(DATED) >= TO_DATE('${DATE}','yyyymmdd')
      and TRUNC(DATED) < TO_DATE('${DATE}','yyyymmdd') + 1