select Infrastructure_Change_ID,Change_Request_Status,Status_Reason,Description,Detailed_Description,ServiceCI,Scheduled_Start_Date,Scheduled_End_Date,Submit_Date,Change_Timing,ASGRP,ASCHG from aradmin.CHG_Infrastructure_Change

